Month8/step1
krekser37/St_burgers pull request #9
Opened 2022-05-21 17:44 UTC by krekser37

2022-05-21 18:18 UTC, kyzinatra commented on src/components/burgerIngredients/BurgerIngredients.jsx
> +  const { ingredients } = useContext(IngredientsContext);
Можно лучше: будет здорово выглядеть если по клику на таб список будет именно  прокручиваться к нужному месту. Это можно сделать с помощью `element.scrollIntoView({ behavior: "smooth" });`

Подробнее: https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-05-21 18:26 UTC, kyzinatra commented on src/components/burgerConstructor/BurgerConstructor.jsx
> +    dispatchTotalPrice({ type: "increase", price: mainBun.price });
Надо исправить: сейчас не совсем верна считается цена. useEffect для цены должен зависеть от `useEffect(() => , [ingredients])`, для того, чтобы при обновлении этого массива цена также пересчитывалась. Стоит учитывать цену булки дважды т.к. булки в конструкторе 2. Для решение этих проблем вместо increase рекомедную написать тип `set` который бы не прибавлял а устанавливал цену. И считать ее в 1 `useEffect` заного при обновлении `ingredients`

2022-05-21 18:26 UTC, kyzinatra commented on src/components/burgerConstructor/BurgerConstructor.jsx
>      [ingredients]
Можно лучше: булка 1 так что можно использовать `.find`

2022-05-21 18:30 UTC, kyzinatra commented on src/components/OrderTotal/OrderTotal.jsx
> +    })
Надо исправить: До открытия модального окна приходится ждать успешного выполнения запроса, это плохо, так как пользователь не понимает что происходит с сайтом. Лучше сразу открыть модальное окно и показать пользователю preloader, чтобы он понимал что все хорошо. А при ошибке показать там же соответствующее уведомление

2022-05-21 18:31 UTC, kyzinatra commented on src/components/app/App.jsx
>        <AppHeader />
Можно лучше: лучше убрать верхний отступ так как его нет в дизайне

2022-05-21 18:38 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Открывать модальное окно с оформлением заказа сразу по клику на кнопку
- Исправить подсчет стоимости

Можно лучше:

- Папку `utils`  лучше расположить в `src/` так как она не является компонентом
- Папку `images` также лучше вынести в `src/`
- Убрать лишние отступы

Что понравилось:

- Грамотное использование `useMemo`
- Хорошая типизация и понятный код
- Очень круто что вы используете `useReducer`

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-05-21 19:27 UTC, krekser37 commented on src/components/app/App.jsx
>        <AppHeader />
в моей фигме он есть. )

2022-05-21 20:33 UTC, kyzinatra commented on src/components/app/App.jsx
>        <AppHeader />
<img width="674" alt="image" src="https://user-images.githubusercontent.com/51288221/169668116-e7be4a76-fd51-49c2-b033-15591433d64c.png">
Странно, у меня нет. Ну хорошо если у вас есть, то можете остаивить

2022-05-24 10:08 UTC, krekser37 commented on src/components/burgerConstructor/BurgerConstructor.jsx
> +    dispatchTotalPrice({ type: "increase", price: mainBun.price });
исправила, надеюсь, я вас верно поняла)

2022-05-24 10:08 UTC, krekser37 commented on src/components/burgerConstructor/BurgerConstructor.jsx
>      [ingredients]
исправила

2022-05-24 11:44 UTC, kyzinatra commented on src/components/burgerConstructor/BurgerConstructor.jsx
> +    });
Надо исправить: Почти верно сделано, только цена должна не складываться с предыдущей, а считаться заново, чтобы при обновлении компонента она не прибавилась к старой. И не получалось такой ситуации, что цена выводится не верно. Я  представляю себе это примерно вот так:
```js
useEffect(() => {
  const totalPrice = filling.reduce(() => {...}, bun.price*2);
  dispatchTotalPrice({ type: "set", payload: totalPrice });
}, [selectIngredients])

```

А в reducer мы бы не прибавляли цену к старой а устанавливали бы новую, актуальную. Тогда при перерендере у нас не возникнет проблем

2022-05-24 11:45 UTC, kyzinatra commented
Вы отлично исправили все ошибки. Осталось только чуть-чуть подкорректировать вывод цены

2022-05-25 09:23 UTC, merged